version: "3"
services:
  restapi:
    image: sjchat-restapi
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 200M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
    depends_on:
      - message-service
      - user-service

  message-service:
    image: sjchat-message-service
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 200M
      restart_policy:
        condition: on-failure
    ports:
      - "50052:50052"
    networks:
      - webnet

  user-service:
    image: sjchat-user-service
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 200M
      restart_policy:
        condition: on-failure
    ports:
      - "50051:50051"
    networks:
      - webnet
networks:
  webnet: